### ISSUE TITLE
重新指定HOST或URL不成功

### ISSUE THREAD

**Issue by huzuli** [whistle-plugins/whistle.script#1]
尝试了以下方法均不能成功：
yield next('http://www.baidu.com');
yield next({host:"www.baidu.com"});
yield next({"www.baidu.com",80});
yield next({url:"http://www.baidu.com"});
yield next("www.baidu.com");

请说明可以将host或url rewrite到其他地址的方法。

**Comment by avwo** [comment]
更新下 `npm i -g whistle.script`，这里用法不对，`yield next(options)`，其中，`options` 只能为以下情景之一：

- 空: 默认请求
- `ip` 或 `ip:port` 或 `{ host: ip, port: port }`: 设置请求的ip及端口
- `{ proxyUrl: 'http://127.0.0.1:8888' }`: 设置请求代理


如果你要进行转发，可以用script里面自带的全局 [request](https://github.com/request/request) 方法来构造新的请求，注意这个请求是在koa的中间件里面执行的，要用 `yield` 或 `await` 处理异步

	const url = require('url');
	
	exports.handleRequest = function* (ctx, next) {
	  const data = yield ctx.getReqForm();
	  console.log(request);
	  console.log(iconv);
	  console.log(ws);
	  // const res = yield next('127.0.0.1:999'); 
	  const res = yield next('127.0.0.1'); 
	};
