### ISSUE TITLE
重新安装whistle.script时装不上了

### ISSUE THREAD

**Issue by JiangChenYang** [whistle-plugins/whistle.script#13]
C:\Users\Administrator> npm install -g whistle
C:\Users\Administrator\AppData\Roaming\npm\whistle -> C:\Users\Administrator\AppData\Roaming\npm\node_modules\whistle\bin\whistle.js
C:\Users\Administrator\AppData\Roaming\npm\wproxy -> C:\Users\Administrator\AppData\Roaming\npm\node_modules\whistle\bin\whistle.js
C:\Users\Administrator\AppData\Roaming\npm\w2 -> C:\Users\Administrator\AppData\Roaming\npm\node_modules\whistle\bin\whistle.js
+ whistle@2.5.19
updated 1 package in 3.363s

C:\Users\Administrator>npm install -g whistle.script
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN whistle.script@0.3.2 requires a peer of whistle@>= 1.12.0 but none is installed. You must install peer dependencies yourself.

+ whistle.script@0.3.2
updated 1 package in 4.406s

whistle 已经安装到最新版 2.5.19   但whistle.script 装不上的样子   提示 whistle.script@0.3.2 requires a peer of whistle@>= 1.12.0 but none is installed. You must install peer dependencies yourself.

插件列表中刷新也没有显示出来

**Comment by avwo** [comment]
这个是警告可以忽略，后面我再去掉这个声明。
