### ISSUE TITLE
插件代理设置的疑惑

### ISSUE THREAD

**Issue by murphysking** [whistle-plugins/whistle.script#15]
<img width="483" alt="截屏2020-09-24 17 59 37" src="https://user-images.githubusercontent.com/22335334/94131165-28b64100-fe90-11ea-9fc7-63c221094455.png">
如图，插件已经设置好代理规则，应该如何添加handleRequest来处理返回消息？README和之前的issue没看明白

**Comment by avwo** [comment]
可以export多个 `exports.handleRequest = (ctx) => {}`
