### ISSUE TITLE
希望作者可以做给一些修改请求的例子

### ISSUE THREAD

**Issue by lueans** [whistle-plugins/whistle.script#17]
```javascript
exports.handleRequest = async (ctx, request) => {
	// ctx.fullUrl 可以获取请求url
	// ctx.headers 可以获取请求头
	// ctx.options 里面包含一些特殊的请求头字段，分别可以获取一些额外信息，如请设置的规则等
	// ctx.method 获取和设置请求方法
	// ctx.req
	// ctx.res
	const { req, res } = ctx;
	const client = request((svrRes) => {
        console.log("-----------------request- svrRes------------------")
        console.log(svrRes)
		res.writeHead(svrRes.statusCode, svrRes.headers);
		svrRes.pipe(res);
		// try {
			// const body = await ctx.getStreamBuffer(svrRes);
			// delete svrRes.headers['content-encoding'];
			// res.writeHead(svrRes.statusCode, svrRes.headers);
			// res.end(body);
		// } catch (err) {}
	});
	req.pipe(client);
};
```
希望作者可以给一些修改请求信息和响应信息的例子

**Comment by avwo** [comment]
可以，你具体想实现什么功能？

**Comment by lueans** [comment]
我想要通过在代理的时候自动注入一些参数，但是这些参数是通过一些规则自动生成的，比如签名，
exports.handleRequest = async (ctx, request) 我想在这里自动注入通用参数

**Comment by lueans** [comment]
还有希望有一些，脚本钩子函数里面的对象的api文档，比如：
exports.handleRequest = async (ctx, request) => {
	// ctx.fullUrl 可以获取请求url
	// ctx.headers 可以获取请求头
	// ctx.options 里面包含一些特殊的请求头字段，分别可以获取一些额外信息，如请设置的规则等
	// ctx.method 获取和设置请求方法
	// ctx.req
	// ctx.res
	const { req, res } = ctx;
	const client = request((svrRes) => {
        console.log("-----------------request- svrRes------------------")
        console.log(svrRes)
		res.writeHead(svrRes.statusCode, svrRes.headers);
		svrRes.pipe(res);
		// try {
			// const body = await ctx.getStreamBuffer(svrRes);
			// delete svrRes.headers['content-encoding'];
			// res.writeHead(svrRes.statusCode, svrRes.headers);
			// res.end(body);
		// } catch (err) {}
	});
	req.pipe(client);
};

ctx，request   req, res  svrRes 这些对象的api，属性or方法

**Comment by avwo** [comment]
大部分是 Node 原生的，参考：https://nodejs.org/dist/latest-v16.x/docs/api/http.html

**Comment by lueans** [comment]
没有看懂文档用户，辛苦大佬帮忙给一些例子
场景如下：
1、修改url 参数
2、修改post body参数

**Comment by avwo** [comment]
一般用Whistle 规则即可 https://wproxy.org/whistle/rules/urlParams.html
https://wproxy.org/whistle/rules/reqMerge.html
https://wproxy.org/whistle/rules/pathReplace.html

**Comment by lueans** [comment]
接口有签名校验，修改参数可以直接用规则，但是需要动态重新签名

**Comment by jonnywang** [comment]
api参数说明太少了

**Comment by lueans** [comment]
> 接口有签名但是，修改参数可以直接使用规则，需要动态 当前公司签名在body和url参数有
