### ISSUE TITLE
handleWebSocket，端口自动修改了

### ISSUE THREAD

**Issue by feijihong** [whistle-plugins/whistle.script#18]
按照文档例子，添加了script
exports.handleWebSocket = async (socket, connect) => {
     ....
}
代理开启，发现请求端口自动修改了？

![image](https://user-images.githubusercontent.com/27736975/153759294-6dce93da-a20d-4ea5-926c-fc5aa6830074.png)
![image](https://user-images.githubusercontent.com/27736975/153760801-8f04596c-b377-40c5-80c2-bc576ce4222e.png)

**Comment by avwo** [comment]
报错了，用 w2 run 启动，并看下控制台

**Comment by feijihong** [comment]
结果一样，端口和原来的不一样

**Comment by feijihong** [comment]
![image](https://user-images.githubusercontent.com/27736975/153762090-13089458-d86e-412d-a431-e491a5af19e1.png)
不好意思，刚刚确认了，是否是这个报错？

**Comment by avwo** [comment]
> ![image](https://user-images.githubusercontent.com/27736975/153762090-13089458-d86e-412d-a431-e491a5af19e1.png) 不好意思，刚刚确认了，是否是这个报错？

是这个问题，发送的数据类型不对

**Comment by feijihong** [comment]
Accept-Encoding | gzip, deflate, br

搜了下，估计是这个原因
继续看文档，去掉它

**Comment by avwo** [comment]
`send(obj)` 改成 `send(JSON.stringify(obj))`

**Comment by feijihong** [comment]
> `send(obj)`改成`send(JSON.stringify(obj))`
![image](https://user-images.githubusercontent.com/27736975/153831737-d9b9fea5-c88b-4139-b0d7-0235b9684023.png)
不行.服务器还是不返回.
![image](https://user-images.githubusercontent.com/27736975/153831971-213ff607-f999-41da-9d8b-37028a0985d5.png)
会不会是请求头的问题呢?

**Comment by avwo** [comment]
删除掉试试 `pattern delete://reqH.accept-encoding`

**Comment by feijihong** [comment]
> 删除掉试试 `pattern delete://reqH.accept-encoding`

还是不行...

奇怪了,LightProxy是怎么做的咧?

**Comment by feijihong** [comment]
> 怎么重现，我这边看下

邮件已发
主题：Websocket抓包问题

**Comment by avwo** [comment]
重新安装插件试试
