### ISSUE TITLE
想知道如何获取req的body内容

### ISSUE THREAD

**Issue by Mrqqeat** [whistle-plugins/whistle.script#21]
不知道要如何获取req的body内容，看demo图片好像是exports.handleRequest 中 ctx.getReqText 来获取。
但是我安装完最新版本的whistle.script后只有exports.handleRequestRules才会有回调，exports.handleRequest则没有反应。。

**Comment by Mrqqeat** [comment]
就知道无脑发帖子了。。没看下面已经有人提问过了，看到下面帖子已经解决了。。。

**Comment by GoodEnoughL** [comment]
> 就知道无脑发帖子了。。没看下面已经有人提问过了，看到下面帖子已经解决了。。。

那你可以close 掉这个issue吗

**Comment by Mrqqeat** [comment]
> > 就知道无脑发帖子了。。没看下面已经有人提问过了，看到下面帖子已经解决了。。。
> 
> 那你可以close 掉这个issue吗

close了
