### ISSUE TITLE
无法打印日志

### ISSUE THREAD

**Issue by gelitenight** [whistle-plugins/whistle.script#3]
script内容如下
```
console.log('test1');
exports.handleRequest = async (ctx, next) => {
   const { statusCode, headers } = await next(); 
   console.log('test2')
   ctx.body = 'abc'
 };
```
结果是，test1会被打印，但是test2始终不打印。`ctx.body = 'abc'`这句已经生效，说明里面的代码是走到了的。
node版本 v9.4.0， whistle版本 1.8.6

**Comment by avwo** [comment]
重新安装下插件 `npm i -g whistle.script`

**Comment by lujqme** [comment]
script 内容如下：
```
exports.handleRequestRules = (ctx) => {
 	ctx.rules = ['www.qq.com file://{test.html}'];
  	ctx.values = { 'test.html': 'Hello world.' };
        console.log(3);
 }; 
console.log(2);
exports.handleRequest = function* (ctx, next) {
   console.log(1);
   const { statusCode, headers } = yield next(); 
   console.log(ctx.fullUrl, statusCode, headers);
 };
```
内容变成了Hello world. 但是console无任何输出。印象中4月份用的时候是正常的，试过了重装

**Comment by lujqme** [comment]
感觉像是console坏掉了？
```
let fs = require('fs');


exports.handleRequestRules = (ctx) => {
 	ctx.rules = ['www.qq.com file://{test.html}'];
  	ctx.values = { 'test.html': 'Hello world.' };
   fs.writeFile('/Users/lujianqiang/Desktop/res.txt', ctx, function (err) {
    if (err) {
        return console.error(err);
    }
    console.log(ctx);
});
 }; 
exports.handleRequest = function* (ctx, next) {
  
   const { statusCode, headers } = yield next(); 
   console.log(ctx.fullUrl, statusCode, headers);
 };
```
fs是能保存的。

**Comment by avwo** [comment]
可能规则配置错了 `pattern script://name`：[操作请求](https://github.com/whistle-plugins/whistle.script#%E6%93%8D%E4%BD%9C%E8%AF%B7%E6%B1%82)

**Comment by lujqme** [comment]
如果配置规则错了的话为什么`exports.handleRequestRules`可以执行？
配置规则写的是 ：
`whistle.script://test www.qq.com`
脚本名为`test`

**Comment by avwo** [comment]
可以执行但不会转发到handleRequest里面，配这个试试`test.www.qq.com script://test`

**Comment by lujqme** [comment]
`test.www.qq.com script://test`
`www.qq.com script://test`
分别都试过了，都不行，handleRequest写什么都没反应，访问的是`www.qq.com`

Whistle Version: 1.11.0
whistle.script 是当前最新版，重装过的

**Comment by avwo** [comment]
我这边是ok的，`scritp://脚本的名称`，脚本名称指下面这段脚本对应的key：
```
console.log('test1');
exports.handleRequest = async (ctx, next) => {
   const { statusCode, headers } = await next(); 
   console.log('test2')
   ctx.body = 'abc'
 }
```
![image](https://user-images.githubusercontent.com/11450939/42493756-c62f1036-8450-11e8-86bb-840fc871fd6d.png)
![image](https://user-images.githubusercontent.com/11450939/42493770-ce62c374-8450-11e8-9660-07385103613f.png)
![image](https://user-images.githubusercontent.com/11450939/42493790-d811ec06-8450-11e8-920b-b6a2cfa4dcbb.png)

**Comment by imcczy** [comment]
node 版本v10.8.0，在mac和Linux下试了都无法输出console.log，确认规则没有问题，exports.handleRequest里的代码能够执行

**Comment by jing2si** [comment]
环境：windows 10，nodejs 10.13.0

**Comment by jing2si** [comment]
还是不行，但是如果script有错误可以显示出来
