### ISSUE TITLE
Websocket 替换服务端返回的status code后会直接断开连接

### ISSUE THREAD

**Issue by muwu711** [whistle-plugins/whistle.script#35]
建立websocket长连接后，拦截长连接里面某条请求的response并替换了status code，websocket长连接直接断开了，帮忙瞧瞧是我脚本写的有问题吗？

```
exports.handleWebSocket = async (socket, connect) => {
	// 与服务器建立连接
	const svrSocket = await connect();
	// 获取客户端解析后的帧数据
	socket.on('message', (data, opts) => {
		console.log(data, 'client data');
		svrSocket.send(data, opts);
	});
    // 获取服务端解析后的帧数据
	svrSocket.on('message', (data, opts) => {
		console.log(data, 'server data');
                if (data.includes('/search')) {       
                    data = data.replace('"status_code":200', '"status_code":503');
                    }
                socket.send(data, opts);
	});
};
```

**Comment by avwo** [comment]
websocket 正常的响应码为 `101`，其它会自动断开

**Comment by muwu711** [comment]
> websocket 正常的响应码为 `101`，其它会自动断开

websocket已经有正常连接上了，然后websocket长连接里的某条请求命中我脚本里面的规则后，尝试去替换data里面的内容并返回给客户端，但websocket长连接直接断开了

**Comment by muwu711** [comment]
我另一台电脑安装的是2.7.3版本的Whistle，可以正常拦截替换，没有出现这个问题，不懂是不是新版本上使用方法有差异

**Comment by avwo** [comment]
列下重现的步骤

**Comment by avwo** [comment]
看下是不是你们的客户端检测到自定义的状态码为 503 主动关闭了请求。

**Comment by muwu711** [comment]
> 看下是不是你们的客户端检测到自定义的状态码为 503 主动关闭了请求。

感谢大佬回复，周末偷懒了，没有上线查看。
我替换的这个状态码不是长连接的状态码，只是长连接里面某个响应体里面后端自定义的一个字段，如果不是替换状态码这个字段，替换其他字段长连接也一样会被close，只要是命中了我脚本里面的规则，长连接就会被断开。

步骤：

1. Plugins 里面添加脚本
```
exports.handleWebSocket = async (socket, connect) => {
	// 与服务器建立连接
	const svrSocket = await connect();
	// 获取客户端解析后的帧数据
	socket.on('message', (data, opts) => {
		console.log(data, 'client data');
		svrSocket.send(data, opts);
	});
	// 获取服务端解析后的帧数据
	svrSocket.on('message', (data, opts) => {
		console.log(data, 'server data');
      	if (data.includes('/api/set_presence')) {       
            data = data.replace('"status_code":200', '"status_code":500');
          }
//       	data = data.replace('"status":200,"headers":{"date":', '"status":503,"headers":{"date":')
		socket.send(data, opts);
	});
};
```
2.Rules里面添加规则： script://Presence wss://xxx.xxx.xxx.net:8443
3. 客户端重新连接Websocket，让规则生效
4. 在客户端修改presence命中脚本里面的规则

问题：命中规则后Websocket长连接直接被断开，未命中规则时数据流都很正常，长连接也一直连着

**Comment by avwo** [comment]
data 打印出来是 string 吗

**Comment by muwu711** [comment]
> data 打印出来是 string 吗
都是如下这种加密的数据
<Buffer 34 32 5b 22 72 65 71 75 65 73 74 22 2c 7b 22 69 64 22 3a 22 31 36 39 37 31 38 39 31 30 37 37 32 38 22 2c 22 70 61 74 68 22 3a 22 2f 61 70 69 2f 63 6f ... 1050 more bytes> client data

**Comment by avwo** [comment]
那就是 `data = data.replace('"status":200,"headers":{"date":', '"status":503,"headers":{"date":')` 这行报错，导致请求中断，改成 `data = String(data).replace('"status":200,"headers":{"date":', '"status":503,"headers":{"date":')` 试试

**Comment by muwu711** [comment]
> 那就是 `data = data.replace('"status":200,"headers":{"date":', '"status":503,"headers":{"date":')` 这行报错，导致请求中断，改成 `data = String(data).replace('"status":200,"headers":{"date":', '"status":503,"headers":{"date":')` 试试

转成string果然可以了，谢谢大佬的解答~
