### ISSUE TITLE
希望能模拟返回eventStream

### ISSUE THREAD

**Issue by Wangggym** [whistle-plugins/whistle.script#37]
<img width="636" alt="image" src="https://github.com/whistle-plugins/whistle.script/assets/26135370/f9658a24-533e-4d85-af21-1bf1d0bcb672">

<img width="766" alt="image" src="https://github.com/whistle-plugins/whistle.script/assets/26135370/90d53118-a8be-4536-80de-9834bfe97e6e">

示例代码不清楚各个参数的含义，这些参数哪儿去找上下文呢？
另外希望能mock 返回 EventStream 数据，请问如何实现？

@avwo @echopi 感激不尽

**Comment by avwo** [comment]
试下这个插件：https://github.com/whistle-plugins/whistle.vase

**Comment by Wangggym** [comment]
@avwo 谢谢，请问下还有相关更具体的例子吗？

**Comment by avwo** [comment]
看 README 的这个例子
<img width="800" alt="image" src="https://github.com/whistle-plugins/whistle.script/assets/11450939/493f62b8-b948-436d-94a0-80e2920c779d">

**Comment by Wangggym** [comment]
还是太模糊了 不会用🤣

**Comment by Wangggym** [comment]
@avwo 类似于实现GPT的返回效果那种

**Comment by Wangggym** [comment]
@avwo @echopi  插件有个问题，获取不了 res 对象， 没法stream 加载
<img width="654" alt="image" src="https://github.com/whistle-plugins/whistle.script/assets/26135370/5214330f-c067-4ffa-9046-306a961edc11">

**Comment by avwo** [comment]
自己写个插件：https://github.com/whistle-plugins/examples

**Comment by Wangggym** [comment]
@avwo script 插件可以mock 
<img width="453" alt="image" src="https://github.com/whistle-plugins/whistle.script/assets/26135370/3fb8551e-34b3-4cf0-a646-4b9b8d098707">
