### ISSUE TITLE
how to print response and request body

### ISSUE THREAD

**Issue by davidjanson2020** [whistle-plugins/whistle.script#4]
is it possible to log request and response body in console?
(like the data in the Inspectors in raw section)

**Comment by echopi** [comment]
Hi:

As `whistle.script` docs shows, there are several methods you can use in ctx param:

```js
exports.handleRequest = async (ctx, next) => {
  // const reqBody = yield ctx.getReqBody();
  // const reqText = yield ctx.getReqText(); 
  // const formData = yield ctx.getReqForm();
  // console.log(reqText)
  const { statusCode, headers } = await next();
  
  // const resBody = yield ctx.getResBody();
  // const resText = yield ctx.getResText();
  // console.log(resText)
};
```

**Comment by Mackerly** [comment]
> Hi:
> 
> As `whistle.script` docs shows, there are several methods you can use in ctx param:
> 
> ```js
> exports.handleRequest = async (ctx, next) => {
>   // const reqBody = yield ctx.getReqBody();
>   // const reqText = yield ctx.getReqText(); 
>   // const formData = yield ctx.getReqForm();
>   // console.log(reqText)
>   const { statusCode, headers } = await next();
>   
>   // const resBody = yield ctx.getResBody();
>   // const resText = yield ctx.getResText();
>   // console.log(resText)
> };
> ```

evalmachine.<anonymous>:12
  const resBody = yield ctx.getResBody();
                        ^^^

SyntaxError: Unexpected identifier

**Comment by echopi** [comment]
alter yield to await, that should be ok

**Comment by avwo** [comment]
Try updating Node.js.

**Comment by ruan11223344** [comment]
获取不到requests body  入口如下
` exports.handleRequestRules = async (ctx,request) => {}`

**Comment by avwo** [comment]
> 获取不到requests body 入口如下 ` exports.handleRequestRules = async (ctx,request) => {}`

这里是获取不到 request body，可以通过 `exports.server` 里面获取

**Comment by ruan11223344** [comment]
哥没问题了,感谢
`
exports.handleRequestRules  = async (ctx, request) =>{
  ctx.req.getReqSession((session) => {
        console.log(session.req.body);
    })
}

`

**Comment by yiqianglin** [comment]
> 哥没问题了,感谢 `exports.handleRequestRules = async (ctx, request) =>{ ctx.req.getReqSession((session) => { console.log(session.req.body); }) }`

log请问再哪里可以看到啊？
