### ISSUE TITLE
包含的lib必须是全局安装的吗？

### ISSUE THREAD

**Issue by gumpjt** [whistle-plugins/whistle.script#6]
如下代码中，打印出的`DB`是空对象。`require` 的包具体有什么要求吗？
```
var path = require('path');
var u = 'D:\\my\\js\\lib';

try{
	var file = path.join(u, './db.js');
	var DB = require(file);
	console.log(JSON.stringify(DB));
}catch(e){
	console.log(e);  
}

exports.handleRequest = function* (ctx, next) {
   const { statusCode, headers } = yield next(); 
};
```

**Comment by avwo** [comment]
你是要保存抓包数据吗，用 `resStatsServer` 里面可以通过 `req.getSession(cb)` 获取请求完整数据包 http://wproxy.org/whistle/plugins.html

whistle.script 里面可以用绝对路径引用

**Comment by avwo** [comment]
```js
exports.resStatsServer = (server) => {
  server.on('request', (req) => {
    req.getSession((session) => {
      // 如果设置了 pattern enable://hide，将无法获取session
      if (!session) {
        return;
      }
      // do sth
      // 如果要获取WebSocket或Socket请求的帧数据，可以通过
      /* req.getFrames((list) => {
        if (!list) {
          // 如果list为空，则表示请求已经结束或该请求只是普通的http请求
          return;
        }
        // 每次会返回 1~16个请求帧数据
        session.frames = list;
        // 如果要请求多个，可以继续调用 req.getFrames
        // req.getFrames(() => { ... })
      }); */
    });
  });
};
```

**Comment by gumpjt** [comment]
> ```js
> exports.resStatsServer = (server) => {
>   server.on('request', (req) => {
>     req.getSession((session) => {
>       // 如果设置了 pattern enable://hide，将无法获取session
>       if (!session) {
>         return;
>       }
>       // do sth
>       // 如果要获取WebSocket或Socket请求的帧数据，可以通过
>       /* req.getFrames((list) => {
>         if (!list) {
>           // 如果list为空，则表示请求已经结束或该请求只是普通的http请求
>           return;
>         }
>         // 每次会返回 1~16个请求帧数据
>         session.frames = list;
>         // 如果要请求多个，可以继续调用 req.getFrames
>         // req.getFrames(() => { ... })
>       }); */
>     });
>   });
> };
> ```

是的，我需要监听某个特定请求，然后把返回保存到数据库中。目前我是根据文档中：
```
exports.handleRequest = async (ctx, next) => {
   // do sth
   // next方法可以设置next({ host, port });
   const { statusCode, headers } = await next(); 
   // do sth
 };
```
这段代码来进行`response`的获取。
上面这段代码与你前面提到的req.getSession都可以获取到吧?

**Comment by avwo** [comment]
都可以

**Comment by gumpjt** [comment]
好的，我了解了，谢谢。

Close it.
