### ISSUE TITLE
一些改进建议

### ISSUE THREAD

**Issue by gumpjt** [whistle-plugins/whistle.script#7]
这几天测了一下，发现：
```
exports.handleRequest = async (ctx, next) => {
   // do sth
   // next方法可以设置next({ host, port });
   const { statusCode, headers } = await next(); 
   // do sth
 };
```
这里的实现方式应该是每当请求来的时候，都会重新把这段代码require一遍吧。如果是这样，当在上述代码中做一些诸如初始化数据库、链接redis等操作的时候，就会产生不小的开销。尤其是请求很多的时候。例如：
```
const DB = require('some-db-client');
const foo = DB.init(''); //做一些同步、有网络开销的事情
exports.handleRequest = async (ctx, next) => {
   // do sth

   const { statusCode, headers } = await next(); 
   foo.save('response data');
   // do sth
 };
```
所以这里的实现逻辑应该为只require一遍并暴露`handleRequest`给框架。这么做可能会更好一些，作者你觉得呢？

**Comment by avwo** [comment]
因为每个请求都会执行一次  `script.runInContext(...)` ，所以会把代码里面的变量重新初始化，可以参考该插件的实现自己写一个whistle插件，这样更灵活，且可以作为独立的npm包。

**Comment by theowenyoung** [comment]
同意楼主的建议. 也许这里可以改进为仿照 [postcss 的插件机制](https://github.com/postcss/postcss/blob/main/docs/writing-a-plugin.md#step-3-find-nodes)

提供`once`,`onceExist`，之类的钩子，供初始化，现在这样确实很难处理初始化和累加之类的东西。
