### ISSUE TITLE
使用script插件篡改响应后导致serverIp和serverPort变化

### ISSUE THREAD

**Issue by zhangwenqiang00** [whistle-plugins/whistle.script#8]
使用script篡改响应成功，但是UI页面上展示的serverIp变成了127.0.0.1，期望能展示原始的server ip。

篡改响应规则如下:
`
exports.handleRequest = async (ctx, next)=>{
  // 检查接口路径是否在修改列表中
  	console.log(ctx.request.req.originalRes);
// 	let allowedFlag = false;
//   	for(let path of allowedPaths){
//     	if(ctx.fullUrl.indexOf(path) > -1){
//         	allowedFlag = true;
//           	break;
//         }
//     }
  	
  	let res = await next();
  	if(!allowedFlag){
      	return;
    }
  
  	let urlObj = url.parse(ctx.fullUrl, true);
  	let callback = urlObj.query.callback;
  	let respBodyText = await ctx.getResText();
  	respBodyText = respBodyText.replace(`/**/${callback}(`, '').replace(');', '');
  	let respBodyObj = JSON.parse(respBodyText);
  	if(respBodyObj.code != 200){
    	console.log("响应结果非200");
      	return;
    }
  	
  	let currentTime = + respBodyObj.data.currentTime;
  	respBodyObj.data['currentTimeMock'] = myTime(currentTime);
  	ctx.body = '/**/' + callback + '(' + JSON.stringify(respBodyObj) + ');';
  	//ctx.body = "test";
}`

![image](https://user-images.githubusercontent.com/16757418/67996783-f013e480-fc8b-11e9-92cf-348838c2b81b.png)

**Comment by avwo** [comment]
下个版本 fix

**Comment by avwo** [comment]
重新安装下插件
